name: MUGEN Stage Studio
options:
  bundleIdPrefix: com.mugen-stage-studio
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_HARDENED_RUNTIME: YES

targets:
  MUGEN Stage Studio:
    type: application
    platform: macOS
    sources:
      - path: MUGEN Stage Studio
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mugen-stage-studio.app
        INFOPLIST_FILE: MUGEN Stage Studio/App/Info.plist
        CODE_SIGN_ENTITLEMENTS: MUGEN Stage Studio/Entitlements/MUGEN Stage Studio.entitlements
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
