//! DEF serialization.
//!
//! Pure string generation over an already-derived stage, so it can be tested
//! without touching a filesystem. Every numeric value written here comes from
//! [`crate::stage::DerivedStage`]; nothing is recomputed, so the file can't
//! disagree with the preview the user approved.

use core::fmt::Write as _;

use crate::stage::{DerivedStage, StageConfig};
use crate::templates::StageTemplate;

/// Render the `.def` body for a stage.
pub fn write_def(
    config: &StageConfig,
    template: &StageTemplate,
    derived: &DerivedStage,
) -> String {
    let mut s = String::with_capacity(1024);

    let name = if config.name.trim().is_empty() {
        "Untitled Stage"
    } else {
        config.name.trim()
    };
    let author = if config.author.trim().is_empty() {
        "unknown"
    } else {
        config.author.trim()
    };

    let _ = writeln!(s, "; Generated by MUGEN Stage Studio.");
    let _ = writeln!(
        s,
        "; Camera values are derived from the {}x{} backdrop - editing them by",
        derived.bg_width, derived.bg_height
    );
    let _ = writeln!(s, "; hand will desynchronise them from the artwork.");
    let _ = writeln!(s);

    let _ = writeln!(s, "[Info]");
    let _ = writeln!(s, "name = \"{}\"", escape(name));
    let _ = writeln!(s, "displayname = \"{}\"", escape(name));
    let _ = writeln!(s, "versiondate = 1.0");
    let _ = writeln!(s, "mugenversion = 1.1");
    let _ = writeln!(s, "author = \"{}\"", escape(author));
    let _ = writeln!(s);

    let _ = writeln!(s, "[Camera]");
    let _ = writeln!(s, "startx = 0");
    let _ = writeln!(s, "starty = 0");
    let _ = writeln!(s, "boundleft = {}", derived.bounds.bound_left);
    let _ = writeln!(s, "boundright = {}", derived.bounds.bound_right);
    let _ = writeln!(s, "boundhigh = {}", derived.bounds.bound_high);
    let _ = writeln!(s, "boundlow = {}", derived.bounds.bound_low);
    let _ = writeln!(s, "tension = {}", template.tension);
    if let Some(ft) = template.floor_tension {
        let _ = writeln!(s, "floortension = {ft}");
    }
    let _ = writeln!(s, "verticalfollow = {}", trim_float(template.vertical_follow));
    let _ = writeln!(s, "tensionhigh = 0");
    let _ = writeln!(s, "tensionlow = 0");
    // Only emit zoom when it is actually enabled. A stage that writes
    // `zoomout = 1` behaves identically but invites someone to edit the number
    // without re-deriving the bounds that depend on it.
    if derived.zoomout < 1.0 || derived.zoomin > 1.0 {
        let _ = writeln!(s, "zoomin = {}", trim_float(derived.zoomin));
        let _ = writeln!(s, "zoomout = {}", trim_float(derived.zoomout));
    }
    let _ = writeln!(s);

    let _ = writeln!(s, "[PlayerInfo]");
    let _ = writeln!(s, "p1startx = -70");
    let _ = writeln!(s, "p1starty = 0");
    let _ = writeln!(s, "p1facing = 1");
    let _ = writeln!(s, "p2startx = 70");
    let _ = writeln!(s, "p2starty = 0");
    let _ = writeln!(s, "p2facing = -1");
    let _ = writeln!(s, "leftbound = -1000");
    let _ = writeln!(s, "rightbound = 1000");
    let _ = writeln!(s);

    let _ = writeln!(s, "[Scaling]");
    let _ = writeln!(s, "topscale = 1");
    let _ = writeln!(s);

    let _ = writeln!(s, "[Bound]");
    let _ = writeln!(s, "screenleft = {}", template.screen_left);
    let _ = writeln!(s, "screenright = {}", template.screen_right);
    let _ = writeln!(s);

    let _ = writeln!(s, "[StageInfo]");
    let _ = writeln!(
        s,
        "localcoord = {}, {}",
        derived.localcoord_w, derived.localcoord_h
    );
    let _ = writeln!(s, "zoffset = {}", derived.zoffset);
    let _ = writeln!(s, "zoffsetlink = 0");
    let _ = writeln!(s, "autoturn = 1");
    let _ = writeln!(s, "resetbg = 1");
    let _ = writeln!(s);

    let _ = writeln!(s, "[Music]");
    match config.music.as_deref().map(str::trim) {
        Some(m) if !m.is_empty() => {
            let _ = writeln!(s, "bgmusic = {m}");
        }
        _ => {
            let _ = writeln!(s, "; bgmusic = sound/yourtrack.ogg");
        }
    }
    let _ = writeln!(s, "bgvolume = 0");
    let _ = writeln!(s);

    let _ = writeln!(s, "[BGdef]");
    let _ = writeln!(s, "spr = {}.sff", sanitize_filename(name));
    let _ = writeln!(s, "debugbg = 0");
    let _ = writeln!(s);

    // The one BG element. `start` is written from the same placement the axis
    // was written from - see the module docs in `geometry` for why they can
    // never be set independently.
    let _ = writeln!(s, "[BG Backdrop]");
    let _ = writeln!(s, "type = normal");
    let _ = writeln!(s, "spriteno = 0, 0");
    let _ = writeln!(s, "; sprite axis in the SFF is {}, {}", derived.axis.x, derived.axis.y);
    let _ = writeln!(s, "start = {}, {}", derived.start.x, derived.start.y);
    let _ = writeln!(s, "delta = 1, 1");
    let _ = writeln!(s, "mask = 0");
    let _ = writeln!(s);

    s
}

fn escape(value: &str) -> String {
    value.replace('"', "'")
}

fn sanitize_filename(name: &str) -> String {
    let cleaned: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if cleaned.is_empty() {
        "stage".to_string()
    } else {
        cleaned
    }
}

/// `0.75` rather than `0.75000000`, and `1` rather than `1.0`.
fn trim_float(v: f32) -> String {
    if (v - v.round()).abs() < f32::EPSILON {
        format!("{}", v.round() as i64)
    } else {
        let s = format!("{v:.4}");
        s.trim_end_matches('0').trim_end_matches('.').to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::stage::{derive, StageConfig};
    use crate::templates;

    fn sample() -> (StageConfig, &'static StageTemplate, DerivedStage) {
        let t = templates::by_id("T3").unwrap();
        let mut c = StageConfig::empty_for_template("T3");
        c.name = "Neon Rooftop".into();
        c.author = "arkany".into();
        c.bg_image_width = Some(1800);
        c.bg_image_height = Some(1050);
        c.floor_y = Some(924);
        let d = derive(&c, t).unwrap();
        (c, t, d)
    }

    #[test]
    fn writes_the_derived_values_not_template_constants() {
        let (c, t, d) = sample();
        let def = write_def(&c, t, &d);

        assert!(def.contains("localcoord = 1280, 720"));
        assert!(def.contains(&format!("boundleft = {}", d.bounds.bound_left)));
        assert!(def.contains(&format!("boundright = {}", d.bounds.bound_right)));
        assert!(def.contains(&format!("boundhigh = {}", d.bounds.bound_high)));
        assert!(def.contains(&format!("zoffset = {}", d.zoffset)));
    }

    /// The regression this whole change exists to prevent.
    #[test]
    fn start_is_never_zero_zero() {
        for t in templates::ALL_TEMPLATES {
            let mut c = StageConfig::empty_for_template(t.id);
            c.bg_image_width = Some(t.recommended_bg_width);
            c.bg_image_height = Some(t.recommended_bg_height);
            let d = derive(&c, t).unwrap();
            let def = write_def(&c, t, &d);

            assert!(
                !def.contains("start = 0, 0\n"),
                "{}: start = 0,0 puts the backdrop above the viewport",
                t.id
            );
            assert!(
                def.contains(&format!("start = 0, {}", t.localcoord_h)),
                "{}: start.y must equal localcoord height",
                t.id
            );
        }
    }

    #[test]
    fn zoom_is_only_written_when_enabled() {
        let (c, t, d) = sample();
        assert!(!write_def(&c, t, &d).contains("zoomout"));

        let mut zoomed = c.clone();
        zoomed.zoomout_override = Some(0.75);
        let zd = derive(&zoomed, t).unwrap();
        let def = write_def(&zoomed, t, &zd);
        assert!(def.contains("zoomout = 0.75"));
        // ...and the bounds written alongside it are the shrunken ones.
        assert!(def.contains(&format!("boundright = {}", zd.bounds.bound_right)));
        assert!(zd.bounds.bound_right < d.bounds.bound_right);
    }

    #[test]
    fn floortension_is_omitted_when_the_template_omits_it() {
        let t2 = templates::by_id("T2").unwrap();
        let mut c = StageConfig::empty_for_template("T2");
        c.bg_image_width = Some(t2.recommended_bg_width);
        c.bg_image_height = Some(t2.recommended_bg_height);
        let d = derive(&c, t2).unwrap();
        assert!(!write_def(&c, t2, &d).contains("floortension"));
    }

    #[test]
    fn blank_metadata_gets_safe_defaults() {
        let t = templates::by_id("T1").unwrap();
        let mut c = StageConfig::empty_for_template("T1");
        c.bg_image_width = Some(640);
        c.bg_image_height = Some(480);
        let d = derive(&c, t).unwrap();
        let def = write_def(&c, t, &d);
        assert!(def.contains("name = \"Untitled Stage\""));
        assert!(def.contains("author = \"unknown\""));
        assert!(def.contains("spr = Untitled_Stage.sff"));
    }

    #[test]
    fn quotes_in_metadata_cannot_break_the_def() {
        let t = templates::by_id("T1").unwrap();
        let mut c = StageConfig::empty_for_template("T1");
        c.name = "The \"Big\" Arena".into();
        c.bg_image_width = Some(640);
        c.bg_image_height = Some(480);
        let d = derive(&c, t).unwrap();
        let def = write_def(&c, t, &d);
        let name_line = def.lines().find(|l| l.starts_with("name = ")).unwrap();
        assert_eq!(name_line.matches('"').count(), 2, "unbalanced quotes: {name_line}");
    }

    #[test]
    fn trim_float_is_readable() {
        assert_eq!(trim_float(1.0), "1");
        assert_eq!(trim_float(0.75), "0.75");
        assert_eq!(trim_float(0.2), "0.2");
    }
}
