//! The stage a user is building, and the fully-derived parameter set that
//! falls out of it.
//!
//! The old `ConformanceState` asked "does this image match the template's
//! required dimensions, and if not can we crop or pad it into shape?" That is
//! the wrong question for the workflow this tool exists to serve: a backdrop
//! generated by an image model comes out at 1536x1024 or 1792x1024 and will
//! never match a hand-picked 1800x1050. Forcing it to meant cropping away the
//! user's artwork, or bailing out with `TooSmall`.
//!
//! The question asked here instead is "is this image big enough to fill the
//! viewport?" If yes, the camera parameters are derived from whatever size it
//! actually is. If no, it is scaled up uniformly until it is. Only an image
//! that cannot be used at all is rejected.

use serde::{Deserialize, Serialize};

use crate::geometry::{
    self, Axis, CameraBounds, Localcoord, Placement, Start,
};
use crate::templates::StageTemplate;

/// A stage in progress. Crosses the Tauri command boundary in both directions.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StageConfig {
    pub name: String,
    pub author: String,
    pub music: Option<String>,
    pub template_id: String,

    pub bg_image_path: Option<String>,
    /// Native pixel dimensions of the imported file, before any scaling.
    pub bg_image_width: Option<u32>,
    pub bg_image_height: Option<u32>,

    /// Floor line, in pixels down from the top of the *native* artwork.
    /// `None` until the user places it; the template's `default_floor_ratio`
    /// seeds the handle.
    pub floor_y: Option<u32>,

    /// Overrides the template's `zoomout` when the user enables stage zoom.
    pub zoomout_override: Option<f32>,
}

impl StageConfig {
    pub fn empty_for_template(template_id: impl Into<String>) -> Self {
        Self {
            name: String::new(),
            author: String::new(),
            music: None,
            template_id: template_id.into(),
            bg_image_path: None,
            bg_image_width: None,
            bg_image_height: None,
            floor_y: None,
            zoomout_override: None,
        }
    }

    pub fn zoomout(&self, template: &StageTemplate) -> f64 {
        self.zoomout_override.unwrap_or(template.zoomout) as f64
    }
}

/// Whether an imported image can be used, and what it costs to use it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "PascalCase")]
pub enum ImportFit {
    NoImage,
    /// Usable. `scale` is `1.0` when the artwork is already large enough.
    #[serde(rename_all = "camelCase")]
    Usable {
        scale: f64,
        scaled_width: u32,
        scaled_height: u32,
        /// True when the image had to be enlarged to cover the viewport.
        /// Upscaling is lossy; the UI should say so.
        upscaled: bool,
    },
    /// The image cannot cover the viewport even scaled — it has no pixels to
    /// spare in one axis and enlarging it further would be absurd.
    #[serde(rename_all = "camelCase")]
    TooSmall {
        min_width: u32,
        min_height: u32,
        required_scale: f64,
    },
}

/// How far we will enlarge a backdrop before calling it unusable. Beyond 2x a
/// generated image is visibly soft at stage scale.
pub const MAX_UPSCALE: f64 = 2.0;

pub fn assess_fit(
    image_width: u32,
    image_height: u32,
    localcoord: Localcoord,
    zoomout: f64,
) -> ImportFit {
    if image_width == 0 || image_height == 0 {
        return ImportFit::NoImage;
    }
    let (min_w, min_h) = geometry::minimum_image_size(localcoord, zoomout);
    let scale = geometry::cover_scale(image_width, image_height, min_w, min_h);

    if scale > MAX_UPSCALE {
        return ImportFit::TooSmall {
            min_width: min_w,
            min_height: min_h,
            required_scale: scale,
        };
    }

    let (scaled_width, scaled_height) = geometry::scaled_size(image_width, image_height, scale);
    ImportFit::Usable {
        scale,
        scaled_width,
        scaled_height,
        upscaled: scale > 1.0,
    }
}

/// Something worth telling the user about the stage they are about to export.
///
/// These are advisory. None of them blocks an export: a stage that cannot
/// scroll is a legitimate stage, it just isn't what most people want.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum WarningCode {
    Upscaled,
    NoHorizontalScroll,
    NoVerticalScroll,
    FloorBelowViewport,
    LifebarOverlap,
    ZoomExposesBottom,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Warning {
    pub code: WarningCode,
    pub message: String,
}

/// Every value the DEF and SFF writers need, derived from one config.
///
/// Nothing here is user-editable except by moving the floor line or changing
/// the zoom, which is the point: there is no path by which a hand-typed bound
/// can disagree with the artwork.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DerivedStage {
    pub localcoord_w: u32,
    pub localcoord_h: u32,

    pub bg_width: u32,
    pub bg_height: u32,
    pub scale: f64,

    pub axis: Axis,
    pub start: Start,
    pub placement: Placement,

    pub bounds: CameraBounds,
    pub zoffset: i32,
    pub floor_y: u32,

    pub zoomin: f32,
    pub zoomout: f32,

    pub warnings: Vec<Warning>,
}

/// Resolve a config against its template. Returns `None` until an image with
/// usable dimensions has been loaded.
pub fn derive(config: &StageConfig, template: &StageTemplate) -> Option<DerivedStage> {
    let (native_w, native_h) = (config.bg_image_width?, config.bg_image_height?);
    let localcoord = template.localcoord();
    let zoomout = config.zoomout(template);

    let (scale, bg_width, bg_height) = match assess_fit(native_w, native_h, localcoord, zoomout) {
        ImportFit::Usable {
            scale,
            scaled_width,
            scaled_height,
            ..
        } => (scale, scaled_width, scaled_height),
        _ => return None,
    };

    // Canonical layout: center-bottom axis, artwork flush with the bottom of
    // the viewport. `start.y` is localcoord.h, never 0.
    let axis = geometry::canonical_axis(bg_width, bg_height);
    let start = geometry::canonical_start(localcoord.h as i32);
    let placement = Placement::resolve(bg_width, bg_height, axis, start);

    let bounds = geometry::derive_bounds_for_placement(placement, localcoord, zoomout);

    // The floor line is stored against the native artwork, so scale it before
    // converting to a screen coordinate.
    let floor_y = match config.floor_y {
        Some(y) => ((y as f64 * scale).round() as u32).min(bg_height),
        None => (bg_height as f64 * template.default_floor_ratio as f64).round() as u32,
    };
    let zoffset = geometry::derive_zoffset(placement, floor_y);

    let mut warnings = Vec::new();

    if scale > 1.0 {
        warnings.push(Warning {
            code: WarningCode::Upscaled,
            message: format!(
                "Backdrop enlarged {:.2}x to {}x{} so it covers the viewport. \
                 Regenerate at {}x{} or larger for a sharper result.",
                scale, bg_width, bg_height, bg_width, bg_height
            ),
        });
    }

    if bounds.bound_right == 0 {
        warnings.push(Warning {
            code: WarningCode::NoHorizontalScroll,
            message: format!(
                "Backdrop is only {}px wide against a {}px viewport, so the camera \
                 cannot scroll sideways. Use a wider image for a stage that pans.",
                bg_width, localcoord.w
            ),
        });
    }

    if bounds.bound_high == 0 {
        warnings.push(Warning {
            code: WarningCode::NoVerticalScroll,
            message: format!(
                "Backdrop is only {}px tall against a {}px viewport, so the camera \
                 cannot rise when characters jump.",
                bg_height, localcoord.h
            ),
        });
    }

    if zoffset >= localcoord.h as i32 {
        warnings.push(Warning {
            code: WarningCode::FloorBelowViewport,
            message: "The floor line sits at or below the bottom of the screen. \
                      Characters will stand off-screen. Drag it onto the ground \
                      in the artwork."
                .to_string(),
        });
    }

    if geometry::head_behind_lifebars(zoffset, localcoord) {
        warnings.push(Warning {
            code: WarningCode::LifebarOverlap,
            message: "The floor line is high enough that characters will be drawn \
                      behind the lifebars. Move it further down the artwork, or \
                      use a backdrop with a lower horizon."
                .to_string(),
        });
    }

    if zoomout < 1.0 && placement.bottom <= localcoord.h as i32 {
        warnings.push(Warning {
            code: WarningCode::ZoomExposesBottom,
            message: "Zoom-out is enabled but the backdrop ends exactly at the \
                      bottom of the screen, so pulling back will show past its \
                      lower edge. Extend the artwork below the floor line."
                .to_string(),
        });
    }

    Some(DerivedStage {
        localcoord_w: localcoord.w,
        localcoord_h: localcoord.h,
        bg_width,
        bg_height,
        scale,
        axis,
        start,
        placement,
        bounds,
        zoffset,
        floor_y,
        zoomin: template.zoomin,
        zoomout: zoomout as f32,
        warnings,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::templates;

    fn config_with(template_id: &str, w: u32, h: u32, floor: Option<u32>) -> StageConfig {
        let mut c = StageConfig::empty_for_template(template_id);
        c.bg_image_path = Some("/tmp/bg.png".into());
        c.bg_image_width = Some(w);
        c.bg_image_height = Some(h);
        c.floor_y = floor;
        c
    }

    /// The exact scenario the tool exists for: an image-model generation at a
    /// size no template ever listed. It should just work.
    #[test]
    fn a_1536x1024_generation_is_usable_as_is() {
        let t = templates::by_id("T3").unwrap();
        let c = config_with("T3", 1536, 1024, Some(900));
        let d = derive(&c, t).expect("should derive");

        assert_eq!(d.scale, 1.0, "already big enough, no resampling");
        assert_eq!(d.bg_width, 1536);
        assert_eq!(d.bg_height, 1024);

        // Bounds follow the real image, not a template constant.
        assert_eq!(d.bounds.bound_right, (1536 - 1280) / 2);
        assert_eq!(d.bounds.bound_left, -d.bounds.bound_right);
        assert!(d.bounds.bound_high < 0);
    }

    /// The regression that motivated this module: axis and start must describe
    /// a backdrop that actually covers the viewport.
    #[test]
    fn derived_placement_always_covers_the_viewport() {
        for t in templates::ALL_TEMPLATES {
            let c = config_with(t.id, t.recommended_bg_width, t.recommended_bg_height, None);
            let d = derive(&c, t).expect("recommended size must derive");

            assert_eq!(
                d.start.y, d.localcoord_h as i32,
                "{}: start.y must be localcoord height, not 0",
                t.id
            );
            assert_eq!(
                d.axis.y, d.bg_height as i32,
                "{}: axis must be center-bottom",
                t.id
            );
            assert_eq!(d.placement.bottom, d.localcoord_h as i32, "{}", t.id);
            assert!(d.placement.top <= 0, "{}: artwork must reach the top", t.id);
            assert!(d.placement.left <= 0 && d.placement.right >= d.localcoord_w as i32 / 2, "{}", t.id);
        }
    }

    /// `boundhigh` may never let the camera travel past the top of the artwork.
    #[test]
    fn bounds_never_exceed_the_artwork() {
        for t in templates::ALL_TEMPLATES {
            for &(w, h) in &[(1536u32, 1024u32), (1920, 1080), (3200, 1200), (2048, 2048)] {
                let c = config_with(t.id, w, h, None);
                let Some(d) = derive(&c, t) else { continue };

                assert!(
                    d.bounds.bound_high >= d.placement.top,
                    "{} @ {w}x{h}: boundhigh {} scrolls past artwork top {}",
                    t.id,
                    d.bounds.bound_high,
                    d.placement.top
                );
                let half_visible = d.localcoord_w as i32 / 2;
                assert!(
                    d.bounds.bound_right + half_visible <= d.placement.right,
                    "{} @ {w}x{h}: boundright scrolls past artwork right edge",
                    t.id
                );
            }
        }
    }

    #[test]
    fn floor_line_drives_zoffset_and_scales_with_the_image() {
        let t = templates::by_id("T3").unwrap();

        // Floor near the bottom of a flush-mounted 1024-tall image: the
        // artwork's top is at 720 - 1024 = -304, so zoffset = -304 + 900.
        let d = derive(&config_with("T3", 1536, 1024, Some(900)), t).unwrap();
        assert_eq!(d.placement.top, -304);
        assert_eq!(d.zoffset, 596);

        // Dragging the line up moves the floor up by the same amount.
        let higher = derive(&config_with("T3", 1536, 1024, Some(800)), t).unwrap();
        assert_eq!(higher.zoffset, 496);
        assert_eq!(d.zoffset - higher.zoffset, 100);
    }

    #[test]
    fn a_small_image_is_upscaled_not_rejected() {
        let t = templates::by_id("T3").unwrap();
        let fit = assess_fit(1024, 576, t.localcoord(), 1.0);
        match fit {
            ImportFit::Usable { upscaled, scaled_width, scaled_height, .. } => {
                assert!(upscaled);
                assert!(scaled_width >= 1280 && scaled_height >= 720);
            }
            other => panic!("expected Usable, got {other:?}"),
        }

        let d = derive(&config_with("T3", 1024, 576, None), t).unwrap();
        assert!(d.warnings.iter().any(|w| w.code == WarningCode::Upscaled));
    }

    #[test]
    fn a_hopeless_image_is_rejected_with_the_size_it_needs() {
        let t = templates::by_id("T4").unwrap();
        match assess_fit(320, 240, t.localcoord(), 1.0) {
            ImportFit::TooSmall { min_width, min_height, .. } => {
                assert_eq!((min_width, min_height), (1920, 1080));
            }
            other => panic!("expected TooSmall, got {other:?}"),
        }
        assert!(derive(&config_with("T4", 320, 240, None), t).is_none());
    }

    #[test]
    fn enabling_zoom_shrinks_the_bounds_and_warns() {
        let t = templates::by_id("T3").unwrap();
        let mut c = config_with("T3", 1800, 1050, None);
        let without = derive(&c, t).unwrap();

        c.zoomout_override = Some(0.75);
        let with = derive(&c, t).unwrap();

        assert!(
            with.bounds.bound_right < without.bounds.bound_right,
            "zoom-out must shrink horizontal scroll: {} vs {}",
            with.bounds.bound_right,
            without.bounds.bound_right
        );
        assert!(with.bounds.bound_high > without.bounds.bound_high);
        assert!(with.warnings.iter().any(|w| w.code == WarningCode::ZoomExposesBottom));
    }

    #[test]
    fn a_high_floor_line_warns_about_lifebars() {
        let t = templates::by_id("T3").unwrap();
        let d = derive(&config_with("T3", 1536, 1024, Some(400)), t).unwrap();
        assert!(d.warnings.iter().any(|w| w.code == WarningCode::LifebarOverlap));
    }

    #[test]
    fn no_image_derives_to_nothing() {
        let t = templates::by_id("T1").unwrap();
        let c = StageConfig::empty_for_template("T1");
        assert!(derive(&c, t).is_none());
        assert_eq!(assess_fit(0, 0, t.localcoord(), 1.0), ImportFit::NoImage);
    }
}
