import Foundation

/// Generates .def stage definition files for MUGEN/IKEMEN GO
/// Supports both fixed resolutions and dynamic bounds for scrolling stages
class DEFGenerator {
    
    /// Generate DEF file content from a stage document
    /// Uses dynamic bounds calculation based on image size for scrolling support
    static func generate(from document: StageDocument, imageSize: CGSize) -> String {
        var lines: [String] = []
        
        let imageWidth = Int(imageSize.width)
        let imageHeight = Int(imageSize.height)
        
        // Determine localcoord based on resolution type
        // For custom/scrolling: always use 1280x720 as localcoord (screen size)
        // For fixed: use the fixed resolution as both image and localcoord
        let localcoordWidth: Int
        let localcoordHeight: Int
        let boundleft: Int
        let boundright: Int
        let boundhigh: Int
        let boundlow: Int
        let zoffset: Int
        let isScrolling: Bool
        
        if document.resolution == .custom {
            // Custom resolution - calculate dynamic bounds for scrolling
            localcoordWidth = 1280
            localcoordHeight = 720
            
            // Camera pan distance = how much image extends beyond screen
            let cameraPanX = max(0, (imageWidth - localcoordWidth) / 2)
            boundleft = -cameraPanX
            boundright = cameraPanX
            
            // Vertical bounds - allow camera to pan up if image is taller
            let cameraPanY = max(0, imageHeight - localcoordHeight)
            boundhigh = -cameraPanY  // Negative = can look up
            boundlow = 0
            
            // zoffset matches the axis Y value for proper alignment
            // Characters stand at zoffset from top of screen
            zoffset = imageHeight + (localcoordHeight - 75)
            
            isScrolling = cameraPanX > 0 || cameraPanY > 0
        } else {
            // Fixed resolution - no scrolling
            localcoordWidth = imageWidth
            localcoordHeight = imageHeight
            boundleft = -128
            boundright = 128
            boundhigh = -25
            boundlow = 0
            // zoffset for fixed stages - matches working stage formula
            zoffset = imageHeight + (localcoordHeight - 75)
            isScrolling = false
        }
        
        // Header comment
        lines.append("; Generated by MUGEN Stage Studio")
        if isScrolling {
            lines.append("; Scrolling stage - image: \(imageWidth)x\(imageHeight), localcoord: \(localcoordWidth)x\(localcoordHeight)")
        } else {
            lines.append("; Fixed resolution: \(imageWidth)x\(imageHeight)")
        }
        lines.append("")
        
        // [Info] section
        lines.append("[Info]")
        lines.append("name = \"\(document.name)\"")
        lines.append("displayname = \"\(document.name)\"")
        lines.append("mugenversion = 1.1")
        lines.append("author = \"MUGEN Stage Studio\"")
        lines.append("")
        
        // [Camera] section
        lines.append("[Camera]")
        lines.append("startx = 0")
        lines.append("starty = 0")
        lines.append("boundleft = \(boundleft)")
        lines.append("boundright = \(boundright)")
        lines.append("boundhigh = \(boundhigh)")
        lines.append("boundlow = \(boundlow)")
        lines.append("tension = 50")
        lines.append("verticalfollow = \(isScrolling ? "0.85" : "0.2")")
        lines.append("floortension = \(isScrolling ? "200" : "160")")
        lines.append("")
        
        // [PlayerInfo] section
        lines.append("[PlayerInfo]")
        lines.append("p1startx = -200")
        lines.append("p1starty = 0")
        lines.append("p1facing = 1")
        lines.append("p2startx = 200")
        lines.append("p2starty = 0")
        lines.append("p2facing = -1")
        lines.append("leftbound = -590")
        lines.append("rightbound = 590")
        lines.append("")
        
        // [Bound] section
        lines.append("[Bound]")
        lines.append("screenleft = 15")
        lines.append("screenright = 15")
        lines.append("")
        
        // [StageInfo] section
        lines.append("[StageInfo]")
        // zoffset: vertical position where characters' feet touch the ground
        // For scrolling stages: imageHeight - 75 (accounts for floor margin)
        // For fixed stages: 660 (near bottom of 720-height screen)
        lines.append("zoffset = \(zoffset)")
        lines.append("autoturn = 1")
        lines.append("resetBG = 1")
        lines.append("localcoord = \(localcoordWidth), \(localcoordHeight)")
        lines.append("portraitscale = 4")
        lines.append("")
        
        // [Shadow] section
        lines.append("[Shadow]")
        lines.append("intensity = 128")
        lines.append("color = 0, 0, 0")
        lines.append("yscale = 0.4")
        lines.append("fade.range = -400, -100")
        lines.append("")
        
        // [Reflection] section
        lines.append("[Reflection]")
        lines.append("reflect = 0")
        lines.append("")
        
        // [BGDef] section
        lines.append("[BGDef]")
        lines.append("spr = \(document.safeName).sff")
        lines.append("debugbg = 0")
        lines.append("")
        
        // Single background layer
        // For scrolling stages: delta=1,1 means 1:1 scrolling with camera
        lines.append("[BG 0]")
        lines.append("type = normal")
        lines.append("spriteno = 0, 0")
        lines.append("start = 0, 0")
        lines.append("delta = 1, 1")
        lines.append("tile = 0, 0")
        lines.append("layerno = 0")
        lines.append("mask = 0")
        lines.append("")
        
        // Stage select thumbnail action
        lines.append("; Stage select thumbnail")
        lines.append("[Begin Action 9000]")
        lines.append("9000,1, 0,0, -1")
        
        return lines.joined(separator: "\n")
    }
}
