import Foundation

/// Generates .def stage definition files for MUGEN/IKEMEN GO
/// Supports dynamic bounds calculation based on image size for scrolling stages
class DEFGenerator {
    
    /// Generate DEF file content from a stage document
    /// Uses dynamic bounds calculation based on image size for scrolling support
    static func generate(from document: StageDocument, imageSize: CGSize) -> String {
        var lines: [String] = []
        
        let imageWidth = Int(imageSize.width)
        let imageHeight = Int(imageSize.height)
        
        // Calculate bounds dynamically based on image size
        // For a 3200px wide image with 1280 localcoord:
        // Extra width = 3200 - 1280 = 1920
        // boundleft = -(extraWidth / 2) = -960
        // boundright = +(extraWidth / 2) = +960
        let localcoordWidth = 1280
        let localcoordHeight = 720
        
        let extraWidth = max(0, imageWidth - localcoordWidth)
        let boundleft = -(extraWidth / 2)
        let boundright = extraWidth / 2
        
        let extraHeight = max(0, imageHeight - localcoordHeight)
        let boundhigh = -(extraHeight / 2)  // Negative = can look up
        let boundlow = 0  // Usually stays at 0
        
        // Header comment
        lines.append("; Generated by MUGEN Stage Studio")
        lines.append("; Dynamic bounds for image size: \(imageWidth)x\(imageHeight)")
        lines.append("")
        
        // [Info] section
        lines.append("[Info]")
        lines.append("name = \"\(document.name)\"")
        lines.append("displayname = \"\(document.name)\"")
        lines.append("mugenversion = 1.1")
        lines.append("author = \"MUGEN Stage Studio\"")
        lines.append("")
        
        // [Camera] section - Dynamic values based on image size
        lines.append("[Camera]")
        lines.append("startx = 0")
        lines.append("starty = 0")
        lines.append("boundleft = \(boundleft)")
        lines.append("boundright = \(boundright)")
        lines.append("boundhigh = \(boundhigh)")
        lines.append("boundlow = \(boundlow)")
        lines.append("tension = 50")
        lines.append("verticalfollow = 0.2")
        lines.append("floortension = 160")
        lines.append("")
        
        // [PlayerInfo] section - Fixed values
        lines.append("[PlayerInfo]")
        lines.append("p1startx = -200")
        lines.append("p1starty = 0")
        lines.append("p1facing = 1")
        lines.append("p2startx = 200")
        lines.append("p2starty = 0")
        lines.append("p2facing = -1")
        lines.append("leftbound = -590")
        lines.append("rightbound = 590")
        lines.append("")
        
        // [Bound] section
        lines.append("[Bound]")
        lines.append("screenleft = 15")
        lines.append("screenright = 15")
        lines.append("")
        
        // [StageInfo] section - Fixed 1280x720 values
        lines.append("[StageInfo]")
        lines.append("zoffset = 660")
        lines.append("autoturn = 1")
        lines.append("resetBG = 1")
        lines.append("localcoord = 1280, 720")
        lines.append("portraitscale = 4")
        lines.append("")
        
        // [Shadow] section
        lines.append("[Shadow]")
        lines.append("intensity = 128")
        lines.append("color = 0, 0, 0")
        lines.append("yscale = 0.4")
        lines.append("fade.range = -400, -100")
        lines.append("")
        
        // [Reflection] section
        lines.append("[Reflection]")
        lines.append("reflect = 0")
        lines.append("")
        
        // [BGDef] section
        lines.append("[BGDef]")
        lines.append("spr = \(document.safeName).sff")
        lines.append("debugbg = 0")
        lines.append("")
        
        // Single background layer with fixed settings
        lines.append("[BG 0]")
        lines.append("type = normal")
        lines.append("spriteno = 0, 0")
        lines.append("start = 0, 0")
        lines.append("delta = 1, 1")
        lines.append("tile = 0, 0")
        lines.append("layerno = 0")
        lines.append("mask = 0")
        lines.append("")
        
        // Stage select thumbnail action
        lines.append("; Stage select thumbnail")
        lines.append("[Begin Action 9000]")
        lines.append("9000,1, 0,0, -1")
        
        return lines.joined(separator: "\n")
    }
}
