import Foundation

/// Generates .def stage definition files for MUGEN/IKEMEN GO
class DEFGenerator {

    // MARK: - Public

    /// Generate DEF file content from a stage document
    static func generate(from document: StageDocument) -> String {
        var lines: [String] = []

        lines.append("; Generated by MUGEN Stage Studio")
        lines.append("")

        appendInfo(to: &lines, document: document)
        appendCamera(to: &lines, document: document)
        appendPlayerInfo(to: &lines, document: document)
        appendBound(to: &lines)
        appendStageInfo(to: &lines, document: document)
        appendShadow(to: &lines, document: document)
        appendReflection(to: &lines)
        if document.targetEngine == .ikemenGo {
            appendMusic(to: &lines)
        }
        appendBGDef(to: &lines, document: document)
        appendBGElements(to: &lines, document: document)
        appendThumbnailAction(to: &lines)

        return lines.joined(separator: "\n")
    }

    // MARK: - Sections

    private static func appendInfo(to lines: inout [String], document: StageDocument) {
        lines.append("[Info]")
        lines.append("name = \"\(document.name)\"")
        lines.append("displayname = \"\(document.name)\"")
        lines.append("mugenversion = \(document.targetEngine.mugenVersion)")
        if document.targetEngine == .ikemenGo {
            lines.append("ikemenversion = 1.0")
        }
        lines.append("author = \"MUGEN Stage Studio\"")
        lines.append("")
    }

    private static func appendCamera(to lines: inout [String], document: StageDocument) {
        let cam = document.camera
        lines.append("[Camera]")
        lines.append("startx = 0")
        lines.append("starty = 0")
        lines.append("boundleft = \(cam.boundLeft)")
        lines.append("boundright = \(cam.boundRight)")
        lines.append("boundhigh = \(cam.boundHigh)")
        lines.append("boundlow = \(cam.boundLow)")
        lines.append("tension = \(cam.tension)")
        lines.append("verticalfollow = \(formatFloat(cam.verticalFollow))")
        lines.append("floortension = \(cam.floorTension)")

        if document.targetEngine.supportsZoom && cam.zoomEnabled {
            lines.append("startzoom = \(formatFloat(cam.zoomStart))")
            lines.append("zoomin = \(formatFloat(cam.zoomMax))")
            lines.append("zoomout = \(formatFloat(cam.zoomMin))")
        }
        lines.append("")
    }

    private static func appendPlayerInfo(to lines: inout [String], document: StageDocument) {
        let p = document.players
        let leftBound = playerWalkBound(for: document, side: -1)
        let rightBound = playerWalkBound(for: document, side: 1)

        lines.append("[PlayerInfo]")
        lines.append("p1startx = \(p.p1X)")
        lines.append("p1starty = 0")
        lines.append("p1facing = \(p.p1Facing)")
        lines.append("p2startx = \(p.p2X)")
        lines.append("p2starty = 0")
        lines.append("p2facing = \(p.p2Facing)")
        lines.append("leftbound = \(leftBound)")
        lines.append("rightbound = \(rightBound)")
        lines.append("")
    }

    private static func appendBound(to lines: inout [String]) {
        lines.append("[Bound]")
        lines.append("screenleft = 15")
        lines.append("screenright = 15")
        lines.append("")
    }

    private static func appendStageInfo(to lines: inout [String], document: StageDocument) {
        lines.append("[StageInfo]")
        lines.append("zoffset = \(document.groundLineY)")
        lines.append("autoturn = 1")
        lines.append("resetBG = 1")
        lines.append("localcoord = \(document.resolution.width), \(document.resolution.height)")
        lines.append("portraitscale = 4")
        lines.append("")
    }

    private static func appendShadow(to lines: inout [String], document: StageDocument) {
        let s = document.shadow
        lines.append("[Shadow]")
        lines.append("intensity = \(s.enabled ? s.intensity : 0)")
        lines.append("color = 0, 0, 0")
        lines.append("yscale = \(formatFloat(s.yscale))")
        if document.targetEngine == .ikemenGo {
            lines.append("fade.range = -400, -100")
        }
        lines.append("")
    }

    private static func appendReflection(to lines: inout [String]) {
        lines.append("[Reflection]")
        lines.append("reflect = 0")
        lines.append("")
    }

    private static func appendMusic(to lines: inout [String]) {
        lines.append("[Music]")
        lines.append("; bgmusic =")
        lines.append("; bgvolume = 100")
        lines.append("")
    }

    private static func appendBGDef(to lines: inout [String], document: StageDocument) {
        lines.append("[BGDef]")
        lines.append("spr = \(document.safeName).sff")
        lines.append("debugbg = 0")
        lines.append("")
    }

    private static func appendBGElements(to lines: inout [String], document: StageDocument) {
        let visibleLayers = document.layers.filter { $0.visible }
        for (i, layer) in visibleLayers.enumerated() {
            lines.append("[BG \(i)]")
            lines.append("type = normal")
            lines.append("spriteno = 0, \(i)")
            lines.append("start = \(formatCoord(layer.position.x)), \(formatCoord(layer.position.y))")
            lines.append("delta = \(formatFloat(Float(layer.delta.x))), \(formatFloat(Float(layer.delta.y)))")
            lines.append("tile = \(layer.tiling.defValue)")
            lines.append("layerno = \(layer.layerIndex)")
            lines.append("mask = 0")
            lines.append("")
        }
    }

    private static func appendThumbnailAction(to lines: inout [String]) {
        lines.append("; Stage select thumbnail")
        lines.append("[Begin Action 9000]")
        lines.append("9000,1, 0,0, -1")
    }

    // MARK: - Helpers

    /// Compute player walk bounds from image half-width minus a margin,
    /// falling back to camera bounds when no image is loaded.
    private static func playerWalkBound(for document: StageDocument, side: Int) -> Int {
        if let imageSize = document.imageSize {
            let half = Int(imageSize.width / 2)
            return side < 0 ? -(half - 50) : (half - 50)
        }
        let screenHalf = Int(document.resolution.size.width / 2)
        return side < 0
            ? document.camera.boundLeft - screenHalf + 50
            : document.camera.boundRight + screenHalf - 50
    }

    /// Format a Float with up to 2 decimal places, dropping unnecessary trailing zeros.
    static func formatFloat(_ value: Float) -> String {
        if value == Float(Int(value)) {
            return String(Int(value))
        }
        return String(format: "%.2f", value)
            .replacingOccurrences(of: #"\.?0+$"#, with: "", options: .regularExpression)
    }

    /// Format a CGFloat coordinate as an integer when it has no fractional part.
    private static func formatCoord(_ value: CGFloat) -> String {
        if value == CGFloat(Int(value)) {
            return String(Int(value))
        }
        return String(format: "%.1f", value)
    }
}
