// Import a backdrop, place the floor, and see what the camera will do.
//
// The old version of this screen asked the image to match the template's exact
// dimensions and refused anything else, which made it unusable for its own
// stated purpose — backdrops generated by an image model never come out at
// 1800x1050. It also gated Continue on a conformance state the backend could
// never return, so the flow dead-ended here.
//
// Now any image that covers the viewport is accepted at whatever size it is,
// and the camera values are derived from that size.

import { useCallback, useEffect, useRef, useState } from "react";
import { deriveStage } from "../hooks/useTauriCommands";
import { StagePreview } from "./StagePreview";
import type { DerivedStage, StageConfig, StageTemplate } from "../types/stage";

interface Props {
  template: StageTemplate;
  config: StageConfig;
  setConfig: (c: StageConfig) => void;
  onBack: () => void;
  onContinue: () => void;
}

const ZOOM_CHOICES = [
  { value: null, label: "No zoom" },
  { value: 0.9, label: "Slight (0.9)" },
  { value: 0.75, label: "Moderate (0.75)" },
  { value: 0.6, label: "Heavy (0.6)" },
];

export function ImageImport({
  template,
  config,
  setConfig,
  onBack,
  onContinue,
}: Props) {
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [derived, setDerived] = useState<DerivedStage | null>(null);
  const [error, setError] = useState<string | null>(null);
  // Drags fire faster than the round trip returns; only the newest wins.
  const requestSeq = useRef(0);

  useEffect(() => {
    return () => {
      if (imageUrl) URL.revokeObjectURL(imageUrl);
    };
  }, [imageUrl]);

  useEffect(() => {
    if (config.bgImageWidth == null || config.bgImageHeight == null) {
      setDerived(null);
      return;
    }
    const seq = ++requestSeq.current;
    deriveStage(config)
      .then((d) => {
        if (seq === requestSeq.current) {
          setDerived(d);
          setError(null);
        }
      })
      .catch((e) => {
        if (seq === requestSeq.current) setError(String(e));
      });
  }, [config]);

  const onFileChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      setError(null);
      const file = e.target.files?.[0];
      if (!file) return;

      const url = URL.createObjectURL(file);
      const probe = new Image();
      probe.onload = () => {
        if (imageUrl) URL.revokeObjectURL(imageUrl);
        setImageUrl(url);
        setConfig({
          ...config,
          // `file.name` is not a real path — the exporter will need one from
          // the dialog plugin. Everything on this screen works from the
          // dimensions alone, so importing is not blocked on that.
          bgImagePath: file.name,
          bgImageWidth: probe.naturalWidth,
          bgImageHeight: probe.naturalHeight,
          floorY: Math.round(probe.naturalHeight * template.defaultFloorRatio),
        });
      };
      probe.onerror = () => {
        URL.revokeObjectURL(url);
        setError("That file could not be read as an image.");
      };
      probe.src = url;
    },
    [config, imageUrl, setConfig, template.defaultFloorRatio],
  );

  const minW = Math.ceil(
    template.localcoordW / (config.zoomoutOverride ?? template.zoomout),
  );
  const minH = Math.ceil(
    template.localcoordH / (config.zoomoutOverride ?? template.zoomout),
  );

  const tooSmall =
    config.bgImageWidth != null &&
    config.bgImageHeight != null &&
    derived == null &&
    error == null;

  return (
    <section className="p-6 max-w-5xl">
      <h1 className="text-xl font-semibold mb-1">Import background</h1>
      <p className="text-sm text-gray-600 mb-4">
        {template.displayName} · viewport {template.localcoordW}×
        {template.localcoordH} · minimum image {minW}×{minH} · suggested{" "}
        {template.recommendedBgWidth}×{template.recommendedBgHeight}
      </p>

      <label className="block mb-4">
        <span className="block text-sm font-medium mb-1">Background image</span>
        <input type="file" accept="image/*" onChange={onFileChange} />
      </label>

      {error && (
        <p className="mb-4 p-3 text-red-700 bg-red-50 border border-red-200 rounded">
          {error}
        </p>
      )}

      {tooSmall && (
        <p className="mb-4 p-3 text-red-700 bg-red-50 border border-red-200 rounded">
          {config.bgImageWidth}×{config.bgImageHeight} is too small to fill this
          viewport. Generate at {minW}×{minH} or larger.
        </p>
      )}

      {imageUrl && derived && (
        <div className="grid gap-6 lg:grid-cols-[2fr_1fr] mb-6">
          <StagePreview
            imageUrl={imageUrl}
            derived={derived}
            nativeHeight={config.bgImageHeight ?? derived.bgHeight}
            onFloorChange={(floorY) => setConfig({ ...config, floorY })}
          />

          <div className="space-y-4">
            <label className="block">
              <span className="block text-sm font-medium mb-1">Stage zoom</span>
              <select
                className="w-full px-3 py-2 border border-gray-300 rounded"
                value={config.zoomoutOverride ?? ""}
                onChange={(e) =>
                  setConfig({
                    ...config,
                    zoomoutOverride:
                      e.target.value === "" ? null : Number(e.target.value),
                  })
                }
              >
                {ZOOM_CHOICES.map((c) => (
                  <option key={c.label} value={c.value ?? ""}>
                    {c.label}
                  </option>
                ))}
              </select>
              <span className="block text-xs text-gray-500 mt-1">
                Zooming out shows more than the viewport, so the camera bounds
                shrink to match. This is why zoom-enabled stages need a larger
                backdrop.
              </span>
            </label>

            <DerivedPanel derived={derived} />
          </div>
        </div>
      )}

      {derived && derived.warnings.length > 0 && (
        <ul className="mb-6 space-y-2">
          {derived.warnings.map((w) => (
            <li
              key={w.code}
              className="p-3 text-sm text-amber-800 bg-amber-50 border border-amber-200 rounded"
            >
              {w.message}
            </li>
          ))}
        </ul>
      )}

      <div className="flex gap-2">
        <button
          type="button"
          onClick={onBack}
          className="px-4 py-2 border border-gray-400 rounded"
        >
          Back
        </button>
        <button
          type="button"
          onClick={onContinue}
          disabled={!derived}
          className="px-4 py-2 bg-blue-600 text-white rounded disabled:bg-gray-300 disabled:cursor-not-allowed"
        >
          Continue
        </button>
      </div>
    </section>
  );
}

function DerivedPanel({ derived }: { derived: DerivedStage }) {
  const rows: [string, string][] = [
    ["localcoord", `${derived.localcoordW}, ${derived.localcoordH}`],
    ["backdrop", `${derived.bgWidth}×${derived.bgHeight}`],
    ["sprite axis", `${derived.axis.x}, ${derived.axis.y}`],
    ["BG start", `${derived.start.x}, ${derived.start.y}`],
    [
      "boundleft / right",
      `${derived.bounds.boundLeft} / ${derived.bounds.boundRight}`,
    ],
    ["boundhigh", `${derived.bounds.boundHigh}`],
    ["zoffset", `${derived.zoffset}`],
  ];

  return (
    <div className="border border-gray-200 rounded bg-gray-50 p-3">
      <h2 className="text-sm font-medium mb-2">Derived parameters</h2>
      <dl className="text-xs font-mono space-y-1">
        {rows.map(([k, v]) => (
          <div key={k} className="flex justify-between gap-3">
            <dt className="text-gray-500">{k}</dt>
            <dd className="text-gray-900">{v}</dd>
          </div>
        ))}
      </dl>
      <p className="text-xs text-gray-500 mt-2">
        Recomputed from the artwork on every change. Axis and start are always
        written as a pair.
      </p>
    </div>
  );
}
