use std::{fs, path::Path};

use crate::templates::StageTemplate;

pub fn write_def(
    output_path: &Path,
    sff_filename: &str,
    stage_name: &str,
    author: &str,
    music: Option<&str>,
    template: &StageTemplate,
) -> Result<(), String> {
    let date = time::OffsetDateTime::now_local()
        .unwrap_or_else(|_| time::OffsetDateTime::now_utc())
        .date();
    let versiondate = format!("{:02},{:02},{}", u8::from(date.month()), date.day(), date.year());
    let floor_tension_line = template
        .floor_tension
        .map(|v| format!("floortension = {v}\n"))
        .unwrap_or_default();
    let music_block = match music.filter(|m| !m.trim().is_empty()) {
        Some(path) => format!("bgmusic = {path}\nbgvolume = 128"),
        None => "bgmusic =".to_string(),
    };
    let safe_stage_name = stage_name.replace('"', "'");
    let safe_author = author.replace('"', "'");

    let contents = format!(
        r#"; Generated by MUGEN Stage Studio
[Info]
name = "{safe_stage_name}"
displayname = "{safe_stage_name}"
versiondate = {versiondate}
mugenversion = 1.1
author = "{safe_author}"
localcoord = {localcoord_w}, {localcoord_h}

[Camera]
startx = 0
starty = 0
boundleft = {bound_left}
boundright = {bound_right}
boundhigh = {bound_high}
boundlow = {bound_low}
verticalfollow = {vertical_follow}
{floor_tension_line}tension = {tension}

[PlayerInfo]
p1startx = -{p_start_x}
p1starty = 0
p1startz = 0
p1facing = 1
p2startx = {p_start_x}
p2starty = 0
p2startz = 0
p2facing = -1
leftbound = -1000
rightbound = 1000
topbound = 0
botbound = 0

[Scaling]
topz = 0
botz = 50
topscale = 1
botscale = 1.2

[Bound]
screenleft = {screen_left}
screenright = {screen_right}
screenbottom = 0

[StageInfo]
zoffset = {zoffset}
autoturn = 1
resetBG = 0

[Shadow]
intensity = 128
color = 0, 0, 0
yscale = 0.4
fade.range = -400, -100

[Reflection]
intensity = 0

[Music]
{music_block}

[BGdef]
spr = {sff_filename}

[BG Main]
type = normal
spriteno = 0, 0
start = 0, {localcoord_h}
delta = 1, 1
layerno = 0
tile = 0, 0
tilespacing = 0, 0
"#,
        localcoord_w = template.localcoord_w,
        localcoord_h = template.localcoord_h,
        bound_left = template.bound_left,
        bound_right = template.bound_right,
        bound_high = template.bound_high,
        bound_low = template.bound_low,
        tension = template.tension,
        vertical_follow = template.vertical_follow,
        screen_left = template.screen_left,
        screen_right = template.screen_right,
        p_start_x = template.localcoord_w / 4,
        zoffset = template.zoffset,
    );

    fs::write(output_path, contents).map_err(|e| format!("Failed to write DEF: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::templates::{T1, T2};
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn writes_template_camera_and_bgdef_values() {
        let dir = tempdir().expect("temp dir");
        let path = dir.path().join("stage.def");

        write_def(&path, "My_Stage.sff", "My Stage", "Tester", None, &T1).expect("write def");

        let text = fs::read_to_string(path).expect("read def");
        assert!(text.contains("name = \"My Stage\""));
        assert!(text.contains("author = \"Tester\""));
        assert!(text.contains("localcoord = 320, 240"));
        assert!(text.contains("boundleft = -152"));
        assert!(text.contains("boundright = 152"));
        assert!(text.contains("boundhigh = -243"));
        assert!(text.contains("boundlow = 0"));
        assert!(text.contains("floortension = 90"));
        assert!(!text.contains("zoffsetlink"));
        assert!(text.contains("p1startx = -80"));
        assert!(text.contains("p1startz = 0"));
        assert!(text.contains("p2startx = 80"));
        assert!(text.contains("screenleft = 25"));
        assert!(text.contains("spr = My_Stage.sff"));
        assert!(text.contains("spriteno = 0, 0"));
        assert!(text.contains("start = 0, 240"));
        assert!(text.contains("layerno = 0"));
    }

    #[test]
    fn omits_floor_tension_when_template_has_none_and_writes_music() {
        let dir = tempdir().expect("temp dir");
        let path = dir.path().join("stage.def");

        write_def(
            &path,
            "Temple.sff",
            "Temple",
            "Tester",
            Some("sound/temple.ogg"),
            &T2,
        )
        .expect("write def");

        let text = fs::read_to_string(path).expect("read def");
        assert!(!text.contains("floortension"));
        assert!(text.contains("bgmusic = sound/temple.ogg"));
        assert!(text.contains("bgvolume = 128"));
    }
}
