// Installing straight into the IKEMEN GO folder that IKEMEN Lab manages.
//
// IKEMEN Lab (github.com/arkany/IKEMEN-LAB) stores the path of the user's
// IKEMEN GO install in its preferences. When it's there, a stage can skip the
// "copy these files and edit select.def" step entirely: write it to
// `stages/<Name>/`, list it under `[ExtraStages]`, and IKEMEN Lab picks it up
// on its next content load (it scans one folder deep and syncs new stages
// into its default collection by itself).

use std::fs;
use std::path::{Path, PathBuf};

use serde::Serialize;

use stage_core::select_def;
use stage_core::stage::{DerivedStage, StageConfig};
use stage_core::templates::StageTemplate;

use crate::export::{self, ExportResult};

pub const BUNDLE_ID: &str = "com.ikemenlab.IKEMENLab";

/// First line of every DEF this app writes (see `stage_core::def`). Used to
/// tell our own earlier export apart from someone else's stage of the same name.
const DEF_SIGNATURE: &[u8] = b"; Generated by MUGEN Stage Studio.";

/// What the UI needs to offer "Install into IKEMEN GO".
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct IkemenLab {
    pub app_path: String,
    /// The IKEMEN GO folder IKEMEN Lab is pointed at, if it has been set up.
    pub ikemen_go_path: Option<String>,
    /// Why installing isn't possible right now, in words for the user.
    /// `None` means ready.
    pub problem: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct InstallResult {
    pub export: ExportResult,
    pub ikemen_go_path: String,
    /// The line in `select.def`, e.g. `stages/Neon/Neon.def`.
    pub entry: String,
    /// False when the stage was already listed (a re-install).
    pub newly_registered: bool,
    /// True when an earlier Stage Studio export of this stage was overwritten.
    pub replaced: bool,
}

/// Look for IKEMEN Lab and the IKEMEN GO folder it manages.
pub fn detect() -> Option<IkemenLab> {
    let app = find_app()?;
    let ikemen = configured_ikemen_path();
    let problem = match &ikemen {
        None => Some("Open IKEMEN Lab and choose your IKEMEN GO folder to install stages directly.".to_string()),
        Some(dir) => check_ikemen_dir(dir).err(),
    };
    Some(IkemenLab {
        app_path: app.display().to_string(),
        ikemen_go_path: ikemen.map(|p| p.display().to_string()),
        problem,
    })
}

#[cfg(target_os = "macos")]
fn find_app() -> Option<PathBuf> {
    let mut candidates = vec![PathBuf::from("/Applications/IKEMEN Lab.app")];
    if let Some(home) = home_dir() {
        candidates.push(home.join("Applications/IKEMEN Lab.app"));
    }
    candidates.into_iter().find(|p| p.is_dir())
}

#[cfg(not(target_os = "macos"))]
fn find_app() -> Option<PathBuf> {
    // IKEMEN Lab is a macOS app.
    None
}

/// Read `ikemenGOPath` from IKEMEN Lab's preferences. Release builds are
/// sandboxed and keep them in their container; development builds use the
/// shared Preferences folder. The container wins because it's what the
/// installed app actually reads.
fn configured_ikemen_path() -> Option<PathBuf> {
    let home = home_dir()?;
    let plists = [
        home.join(format!(
            "Library/Containers/{BUNDLE_ID}/Data/Library/Preferences/{BUNDLE_ID}.plist"
        )),
        home.join(format!("Library/Preferences/{BUNDLE_ID}.plist")),
    ];
    plists.iter().filter(|p| p.is_file()).find_map(|plist| {
        // `plutil` reads binary and XML plists alike, so no plist crate needed.
        let out = std::process::Command::new("/usr/bin/plutil")
            .args(["-extract", "ikemenGOPath", "raw", "-o", "-"])
            .arg(plist)
            .output()
            .ok()?;
        let path = String::from_utf8(out.stdout).ok()?;
        let path = path.trim();
        (out.status.success() && !path.is_empty()).then(|| PathBuf::from(path))
    })
}

fn home_dir() -> Option<PathBuf> {
    std::env::var_os("HOME").map(PathBuf::from)
}

fn check_ikemen_dir(dir: &Path) -> Result<(), String> {
    if !dir.is_dir() {
        return Err(format!(
            "IKEMEN Lab points at {}, which no longer exists. Choose your IKEMEN GO folder again in IKEMEN Lab.",
            dir.display()
        ));
    }
    if !dir.join("data/select.def").is_file() {
        return Err(format!(
            "{} doesn't look like an IKEMEN GO folder (no data/select.def).",
            dir.display()
        ));
    }
    Ok(())
}

/// Write the stage into `<ikemen>/stages/<stem>/` and list it in `select.def`.
///
/// Re-installing a stage this app made replaces it in place. A folder of the
/// same name holding anything else is left alone and reported, so installing
/// can never overwrite a stage the user got from somewhere else.
pub fn install(
    config: &StageConfig,
    template: &StageTemplate,
    derived: &DerivedStage,
    ikemen_dir: &Path,
) -> Result<InstallResult, String> {
    check_ikemen_dir(ikemen_dir)?;

    let stem = export::file_stem(&config.name);
    let stage_dir = ikemen_dir.join("stages").join(&stem);
    let def_path = stage_dir.join(format!("{stem}.def"));

    let replaced = if def_path.is_file() {
        let existing = fs::read(&def_path)
            .map_err(|e| format!("Could not read {}: {e}", def_path.display()))?;
        if !existing.starts_with(DEF_SIGNATURE) {
            return Err(taken(&stem));
        }
        true
    } else {
        let occupied = fs::read_dir(&stage_dir)
            .map(|mut entries| entries.next().is_some())
            .unwrap_or(false);
        if occupied {
            return Err(taken(&stem));
        }
        false
    };

    let exported = export::export_stage(config, template, derived, &stage_dir)?;

    let entry = select_def::stage_entry(&stem);
    let select_path = ikemen_dir.join("data/select.def");
    let current = fs::read(&select_path)
        .map_err(|e| format!("Could not read {}: {e}", select_path.display()))?;
    let newly_registered = match select_def::add_extra_stage(&current, &entry) {
        None => false,
        Some(updated) => {
            write_atomically(&select_path, &updated).map_err(|e| {
                format!(
                    "The stage files were saved to {}, but {} couldn't be updated ({e}). Add \"{entry}\" under [ExtraStages] yourself to play it.",
                    stage_dir.display(),
                    select_path.display()
                )
            })?;
            true
        }
    };

    Ok(InstallResult {
        export: exported,
        ikemen_go_path: ikemen_dir.display().to_string(),
        entry,
        newly_registered,
        replaced,
    })
}

fn taken(stem: &str) -> String {
    format!(
        "IKEMEN GO already has a stage folder called \"{stem}\" that wasn't made here. Rename your stage to install it alongside."
    )
}

/// Write via a sibling temp file and rename, so a failure part-way through
/// can't leave the game with a truncated `select.def`.
fn write_atomically(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    let tmp = path.with_extension("def.mss-tmp");
    fs::write(&tmp, bytes)?;
    fs::rename(&tmp, path).inspect_err(|_| {
        let _ = fs::remove_file(&tmp);
    })
}

/// Bring IKEMEN Lab to the front (launching it if needed).
pub fn open_app() -> Result<(), String> {
    if !cfg!(target_os = "macos") {
        return Err("IKEMEN Lab is only available on macOS".to_string());
    }
    let status = std::process::Command::new("/usr/bin/open")
        .args(["-b", BUNDLE_ID])
        .status()
        .map_err(|e| format!("Could not open IKEMEN Lab: {e}"))?;
    if status.success() {
        Ok(())
    } else {
        Err("Could not open IKEMEN Lab".to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use stage_core::{stage, templates};

    fn fixture_ikemen(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("mss-ikemen-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(dir.join("data")).unwrap();
        fs::create_dir_all(dir.join("stages")).unwrap();
        fs::write(dir.join("data/select.def"), "[Characters]\nkfm\n\n[ExtraStages]\nstages/stage0.def\n").unwrap();
        dir
    }

    fn stage_config(dir: &Path, name: &str) -> (StageConfig, &'static StageTemplate, DerivedStage) {
        let template = templates::by_id("T3").unwrap();
        let img_path = dir.join("bg.png");
        let (w, h) = (template.recommended_bg_width, template.recommended_bg_height);
        image::RgbaImage::new(w, h).save(&img_path).unwrap();
        let mut config = StageConfig::empty_for_template(template.id);
        config.name = name.to_string();
        config.bg_image_path = Some(img_path.display().to_string());
        config.bg_image_width = Some(w);
        config.bg_image_height = Some(h);
        config.floor_y = Some((h as f64 * template.default_floor_ratio as f64).round() as u32);
        let derived = stage::derive(&config, template).expect("derivable");
        (config, template, derived)
    }

    #[test]
    fn installs_into_its_own_folder_and_registers_once() {
        let ikemen = fixture_ikemen("fresh");
        let (config, template, derived) = stage_config(&ikemen, "Neon Rooftop");

        let first = install(&config, template, &derived, &ikemen).unwrap();
        assert_eq!(first.entry, "stages/Neon_Rooftop/Neon_Rooftop.def");
        assert!(first.newly_registered);
        assert!(!first.replaced);
        assert!(ikemen.join("stages/Neon_Rooftop/Neon_Rooftop.def").is_file());
        assert!(ikemen.join("stages/Neon_Rooftop/Neon_Rooftop.sff").is_file());

        // Exporting again updates the files in place without a second listing.
        let second = install(&config, template, &derived, &ikemen).unwrap();
        assert!(!second.newly_registered);
        assert!(second.replaced);
        let select = fs::read_to_string(ikemen.join("data/select.def")).unwrap();
        assert_eq!(select.matches("stages/Neon_Rooftop/Neon_Rooftop.def").count(), 1);

        let _ = fs::remove_dir_all(&ikemen);
    }

    #[test]
    fn refuses_to_overwrite_a_stage_it_did_not_make() {
        let ikemen = fixture_ikemen("taken");
        let (config, template, derived) = stage_config(&ikemen, "Dojo");
        let theirs = ikemen.join("stages/Dojo");
        fs::create_dir_all(&theirs).unwrap();
        fs::write(theirs.join("Dojo.def"), "[Info]\nname = \"Someone else's dojo\"\n").unwrap();

        let err = install(&config, template, &derived, &ikemen).unwrap_err();
        assert!(err.contains("already has a stage folder"), "{err}");
        assert_eq!(
            fs::read_to_string(theirs.join("Dojo.def")).unwrap(),
            "[Info]\nname = \"Someone else's dojo\"\n"
        );

        let _ = fs::remove_dir_all(&ikemen);
    }

    #[test]
    fn rejects_a_folder_without_select_def() {
        let dir = std::env::temp_dir().join(format!("mss-not-ikemen-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        assert!(check_ikemen_dir(&dir).unwrap_err().contains("doesn't look like"));
        let _ = fs::remove_dir_all(&dir);
    }
}
